# Mysql数据库配置
mysql:
  debug: true # mysql 调试开关
  mysql_dbs:
      name: default
      ip: 192.168.11.244
      port: 3306
      db: ipcc
      user: root
      password: Aa123456!@#

# Redis数据库配置
redis:
  ip: 127.0.0.1:16379
  password: QyHaDrgRn@9p


black_service:
  voice:
    start: true
    accessId: 10007
    accessKey: NQWhPAPZ
  sms:
    start: false
    accessId: 10001
    accessKey: IWmfSOq9
  url: http://47.94.150.29:8099/data/verify
  number-per-request: 1000


common:
  dsid: 98  #设备Id号 取值范围:0-1024
  accessKey: g2Wdj4ya93@7

